Section "Device"
    Identifier "Card0"
    Driver "nvidia"
    Option "MetaModes" "1920x1080, 2560x1440, 1280x720"
    Option "ConnectedMonitor" "DP-0"
    Option "ModeValidation" "NoDFPNativeResolutionCheck,NoVirtualSizeCheck,NoMaxPClkCheck,NoHorizSyncCheck,NoVertRefreshCheck,NoWidthAlignmentCheck"
EndSection
Section "Screen"
    Identifier "metaScreen"
    Device "Card0"
    DefaultDepth 24
    Option "TwinView" "True"
    SubSection "Display"
        Modes "1920x1080"
    EndSubSection
EndSection
